#@+leo-ver=4
#@+node:@file Makefile
# Makefile for PhoneBookFS

default:
	@echo "make: available targets:"
	@echo "  - build - build required packages"
	@echo "  - install - installs packages as root (invokes 'su')"
	@echo "  - clean - cleans package dirs"

build:
	python make.py build

install:
	python make.py install

clean:
	python make.py clean
#@-node:@file Makefile
#@-leo
