#!/usr/bin/env python
#@+leo-ver=4
#@+node:@file util/listmap
#@@first

import sys, os

import pbdummy
sys.path.append(os.path.split(os.path.split(os.path.abspath(pbdummy.__file__))[0])[0])
import pbcmds

argv = sys.argv
argc = len(argv)
progname = argv[0]

def usage(ret=0):
    print "usage: %s mountpoint" % progname
    sys.exit(1)

def main():
    if argc != 2:
        usage(1)
    
    mountpoint = argv[1]    
    res = pbcmds.sendPbCommand(mountpoint,
                               command='listmap',
                               )
    #print "got: %s" % res
    print "PhoneBookFS Layer Map Report:"
    print "  Mountpoint: %s" % mountpoint
    print "  Map Name:   %s" % res['mapname']
    print "  Layers:     %s" % ":".join(res['layers'].split("/"))
    
if __name__ == '__main__':
    main()
#@-node:@file util/listmap
#@-leo
